
# RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_DRIVER = IS31FL3731
# RGBLIGHT_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
OS_DETECTION_ENABLE = yes
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
